version: 0.2

phases:
  install:
    commands:
      - echo "Installing Node.js dependencies"
      - npm install
  build:
    commands:
      - echo "Packaging for CodeDeploy"

artifacts:
  files:
    - '**/*'
  discard-paths: no